apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
        containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - mountPath: /etc/nginx
            name: nginx-conf
        volumes:
        - name: nginx-conf
          configMap: 
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf