apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-service
  name: nginx-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
      - name: nginx-service
        image: nginx
        ports:
            - containerPort: 80
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-configmap
---
apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
    
        upstream main {
            # automate round robin concepts			
            server service/main-service:8080;				
        }
        
        server {            
            listen 80;
            server_name localhost;

            location / {
                proxy_pass http://main;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
